連絡先DAOのテスト起動用ファイル(java)
連絡先DAOが起動するかテスト用のjavaファイル。
現在ID取得はできるが、全表示ができない。
エラーメッセージによれば、SQLの取得がうまくいっていない模様。

コンソールに表示されるメッセージ
↓
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
名前：石田
電話番号：09011112222
メールアドレス：abc@gmail.com
登録日：2020-04-01
SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'contact where contact.id' at line 1
SQLState: 42000
VendorError: 1064
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'contact where contact.id' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
	at dao.ContactDAO.getAllContact(ContactDAO.java:82)
	at test.TestContactDAO.main(TestContactDAO.java:34)
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'contact where contact.id' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
	at dao.ContactDAO.getAllContact(ContactDAO.java:82)
	at test.TestContactDAO.main(TestContactDAO.java:34)